version: "3.9"

volumes:
  pg_data:
  mongo:
  mongo_conf:

services:
  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    restart: always
    image: ${PROJECT_DIR}_ml
    ports:
      - "10000:10000"

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - mongo_conf:/data/configdb

  pg:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    restart: always
    image: ${PROJECT_DIR}_backend
    depends_on:
      - pg
      - mongo
      - ml
    ports:
      - "9999:9999"
    command: ./main
